python3 finetune.py --config-name=musicgen_small_null_unconditional
python3 finetune.py --config-name=musicgen_small_null_unconditional_augmentations
python3 finetune.py --config-name=musicgen_small_default_unconditional_augmentations