name: musicgen_medium_conditional_augmentations

model:
  name: musicgen
  size: medium
  path: ../models/continuous

dataset:
  path: ../data/audio
  sample_rate: 32000
  sources: [dropbox, flat]
  augmentations: [pitch_shift, speed_up]

  skips: [
    dropbox/012.wav dropbox/013.wav dropbox/020.wav dropbox/021.wav dropbox/022.wav
    dropbox/024.wav dropbox/025.wav dropbox/026.wav dropbox/027.wav dropbox/028.wav
    dropbox/029.wav dropbox/030.wav dropbox/031.wav dropbox/032.wav dropbox/033.wav
    dropbox/034.wav dropbox/069.wav dropbox/112.wav dropbox/113.wav dropbox/114.wav
    dropbox/128.wav
  ]

  conditions: description
  description: ../data/descriptions
  inference: ../data/inferences

training:
  device: cuda
  batch_size: 2
  num_workers: 4

  optimizer: AdamW
  lr: 1e-5
  betas: [0.9, 0.95]
  weight_decay: 0.01

  num_epochs: 10

inference:
  path: ../samples/continuous
  num_samples: 10
  durations: [28]
